[package]
name = "dvsa-production-owner-recovery"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[features]
default = ["legacy-rand"]
legacy-rand = ["dep:rand"]
android-rand = ["dep:rand_android"]

[dependencies]
data_model = { path = "../../../common/data_model" }
zerocopy = { version = "=0.8.14", features = ["derive"] }
rand = { version = "0.8", optional = true }
rand_android = { package = "rand", version = "0.9", optional = true }
anyhow = "1"
parking_lot = "0.12"
